env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-essential
  - './.eslintrc-auto-import.json'
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  project: './tsconfig.json'
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions: ['.vue']
ignorePatterns:
  - components.d.ts
  - vite.config.ts
plugins:
  - vue
rules: {
  'vue/multi-word-component-names': 0,
  '@typescript-eslint/no-floating-promises': 0,
  '@typescript-eslint/no-non-null-assertion': 0,
  '@typescript-eslint/triple-slash-reference': 0,
  '@typescript-eslint/consistent-type-assertions': 0,
  '@typescript-eslint/strict-boolean-expressions': 0,
  '@typescript-eslint/explicit-function-return-type': 0,
  '@typescript-eslint/promise-function-async': 0
}
