/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    CommonAside: typeof import('./src/components/common/aside/index.vue')['default']
    CommonAsideSubMenu: typeof import('./src/components/common/aside/SubMenu.vue')['default']
    CommonForm: typeof import('./src/components/common/form/index.vue')['default']
    CommonHeader: typeof import('./src/components/common/header/index.vue')['default']
    CommonHeaderLogo: typeof import('./src/components/common/header/Logo.vue')['default']
    CommonHeaderTheme: typeof import('./src/components/common/header/theme.vue')['default']
    CommonHeaderUserInfo: typeof import('./src/components/common/header/UserInfo.vue')['default']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    LayoutDefault: typeof import('./src/components/layout/Default.vue')['default']
    LayoutPlain: typeof import('./src/components/layout/Plain.vue')['default']
    LoginOutlined: typeof import('@ant-design/icons-vue')['LoginOutlined']
    PieChartOutlined: typeof import('@ant-design/icons-vue')['PieChartOutlined']
    ReloadOutlined: typeof import('@ant-design/icons-vue')['ReloadOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveOutlined: typeof import('@ant-design/icons-vue')['SaveOutlined']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
